spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Mysql Settings
    url: jdbc:mysql://localhost:3306/ttocket?serverTimezone=UTC&characterEncoding=UTF-8
    username: ttocket
    password: '1Q2w3e4r,'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
          format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.ssafy.ttocket: debug